accelerate launch train_controlnet_w_additional.py \
 --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1" \
 --output_dir="model_out_w_additional_canny_mask_10000" \
 --dataset_name=/srv/datasets3/HoliCity/dataset_w_vpts_ang-5 \
 --conditioning_image_column=conditioning \
 --image_column=image \
 --caption_column=caption \
 --resolution=512 \
 --learning_rate=1e-5 \
 --train_batch_size=1 \
 --num_train_epochs=10000 \
 --tracker_project_name="controlnet" \
 --enable_xformers_memory_efficient_attention \
 --checkpointing_steps=5000 \
